### ISSUE TITLE
您好，请问一下如何使用用户自定义词典？

### ISSUE THREAD

**Issue by by2101** [haobibo/ICTCLAS_Python_Wrapper#1]
您好！
我在使用您的分词软件，觉得很好用很方便，非常感谢！
最近想使用用户自定义词典，应该是采用
ImportUserDict = loadFun('NLPIR_ImportUserDict',c_uint, [c_char_p])
这个函数。但是demo中没有例子，所以没有学会用法，请问这个函数如何使用？
谢谢！

**Comment by jhsea3do** [comment]
ImportUserDict('./dict.txt')

dict.txt 的内容是 utf8 的词典， 一行一个词，词语和词性(n/v/....)用tab隔开
